/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e1e0ff",
        "surface-dim": "#dcd9de",
        "on-secondary-fixed-variant": "#862200",
        "surface-container-highest": "#e4e1e7",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container": "#f0edf2",
        "primary-container": "#2e3192",
        "tertiary": "#002e2e",
        "outline": "#777683",
        "inverse-on-surface": "#f3f0f5",
        "on-error-container": "#93000a",
        "outline-variant": "#c7c5d4",
        "surface-tint": "#4f54b4",
        "tertiary-container": "#004646",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f2f8",
        "on-background": "#1b1b1f",
        "error": "#ba1a1a",
        "secondary": "#b02f00",
        "surface": "#fbf8fe",
        "secondary-fixed": "#ffdbd1",
        "inverse-primary": "#c0c1ff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#002020",
        "primary": "#15157d",
        "on-surface": "#1b1b1f",
        "on-surface-variant": "#464652",
        "surface-variant": "#e4e1e7",
        "background": "#fbf8fe",
        "surface-bright": "#fbf8fe",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#93f2f2",
        "on-secondary-fixed": "#3b0900",
        "on-tertiary-fixed-variant": "#004f4f",
        "inverse-surface": "#303034",
        "on-tertiary-container": "#57b8b8",
        "on-primary-container": "#9da1ff",
        "on-secondary-container": "#541100",
        "on-primary-fixed": "#04006d",
        "error-container": "#ffdad6",
        "surface-container-high": "#eae7ed",
        "tertiary-fixed-dim": "#76d6d5",
        "secondary-fixed-dim": "#ffb5a0",
        "secondary-container": "#ff5722",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#373a9b"
      },
      fontFamily: {
        "headline": ["'Plus Jakarta Sans'", 'sans-serif'],
        "body": ["'Inter'", 'sans-serif'],
        "label": ["'Inter'", 'sans-serif']
      }
    },
  },
  plugins: [],
}

